#
# Generated by zgen.
# This file will be overwritten the next time you run zgen save

ZSH=/home/oliver/.zgen/robbyrussell/oh-my-zsh-master

#
source "/home/oliver/.zgen/zsh-users/zsh-syntax-highlighting-master/zsh-syntax-highlighting.plugin.zsh"
source "/home/oliver/.zgen/nojhan/liquidprompt-master/liquidprompt.plugin.zsh"
source "/home/oliver/.zgen/chrissicool/zsh-256color-master/zsh-256color.plugin.zsh"

#
# Add our plugins and completions to fpath
#
fpath=(/home/oliver/.zgen/zsh-users/zsh-syntax-highlighting-master /home/oliver/.zgen/nojhan/liquidprompt-master /home/oliver/.zgen/chrissicool/zsh-256color-master /home/oliver/.zgen/zsh-users/zsh-completions-master/src ${fpath})
